#!/bin/bash
# ==============================================================================
# Title: Comfuzio's Native K3s External IP Fix for Dune: Awakening
# Description: Automates the native configuration of K3s to properly advertise 
#              a Public WAN IP for self-hosted matchmaking, completely bypassing 
#              the need for complex iptables routing hacks.
# License: GNU AGPLv3
# ==============================================================================

set -e

# --- Pre-Flight Checks ---
if [ "$(id -u)" -ne 0 ]; then
    echo "[-] Error: This network tool requires root privileges. Run with sudo."
    exit 1
fi

if ! command -v k3s &> /dev/null; then
    echo "[-] Error: K3s is not installed or not found in PATH."
    exit 1
fi

echo "================================================================"
echo "      Comfuzio's Native K3s Dune: Awakening Network Fix         "
echo "================================================================"

# --- Dynamic IP Detection ---
echo "[+] Detecting network topology..."

# 1. Fetch Public IP
PUBLIC_IP=$(curl -s --connect-timeout 5 https://ifconfig.me)
if [ -z "$PUBLIC_IP" ]; then
    echo "[-] Warning: Primary API failed. Trying fallback..."
    PUBLIC_IP=$(curl -s --connect-timeout 5 https://api.ipify.org)
fi

if [ -z "$PUBLIC_IP" ]; then
    echo "[-] Error: Failed to detect Public WAN IP. Check your internet."
    exit 1
fi

# 2. Fetch Active LAN IP (Finds the IP used by the default gateway)
DEFAULT_IFACE=$(ip route show default | awk '/default/ {print $5}' | head -n1)
LAN_IP=$(ip -4 addr show "$DEFAULT_IFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

if [ -z "$LAN_IP" ]; then
    echo "[-] Error: Failed to detect internal LAN IP on interface $DEFAULT_IFACE."
    exit 1
fi

echo "[*] Discovered Public WAN IP : $PUBLIC_IP"
echo "[*] Discovered Local LAN IP  : $LAN_IP (via $DEFAULT_IFACE)"
echo ""

# --- Configuration Backup & Injection ---
K3S_DIR="/etc/rancher/k3s"
CONFIG_FILE="$K3S_DIR/config.yaml"

mkdir -p "$K3S_DIR"

if [ -f "$CONFIG_FILE" ]; then
    BACKUP_NAME="config.yaml.backup.$(date +%s)"
    cp "$CONFIG_FILE" "$K3S_DIR/$BACKUP_NAME"
    echo "[+] Existing K3s config detected. Backup saved as: $BACKUP_NAME"
fi

echo "[+] Generating native K3s routing configuration..."

cat <<EOF > "$CONFIG_FILE"
# Generated by Comfuzio's Dune: Awakening Network Tool
node-ip: $LAN_IP
node-external-ip: $PUBLIC_IP
advertise-address: $LAN_IP
tls-san:
  - $PUBLIC_IP
  - $LAN_IP
EOF

echo "[*] Configuration written successfully."

# --- Service Management ---
echo ""
echo "[+] Restarting K3s engine to apply topology changes..."
systemctl restart k3s

echo "[+] Waiting for K3s API to come online..."
ATTEMPTS=0
MAX_ATTEMPTS=30

while ! kubectl get nodes &> /dev/null; do
    printf "."
    sleep 2
    ATTEMPTS=$((ATTEMPTS+1))
    if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
        echo ""
        echo "[-] Timeout: K3s took too long to respond. Please check 'systemctl status k3s'."
        exit 1
    fi
done

echo ""
echo "[*] K3s API is responsive!"

# --- Verification Phase ---
echo ""
echo "================================================================"
echo " SUCCESS: SERVER TOPOLOGY RECONFIGURED NATIVELY"
echo "================================================================"
echo " Validation Check:"
NODE_INTERNAL=$(kubectl get nodes -o wide | tail -n +2 | awk '{print $6}')
NODE_EXTERNAL=$(kubectl get nodes -o wide | tail -n +2 | awk '{print $7}')

echo " -> Expected External IP : $PUBLIC_IP"
echo " -> K3s Registered IP    : $NODE_EXTERNAL"

if [ "$PUBLIC_IP" = "$NODE_EXTERNAL" ]; then
    echo ""
    echo " [OK] The K3s node is now properly advertising to the internet."
    echo "      Dune: Awakening players can now connect natively!"
else
    echo ""
    echo " [WARNING] Mismatch detected. Ensure your server doesn't have multiple nodes."
fi
echo "================================================================"
